dataset:
    competition_dir: /kaggle/input/child-mind-institute-detect-sleep-states
    cv_split_path: /kaggle/input/cv-split/train_folds.csv
    train_base_path: /kaggle/input/train_base/train_base.csv
    step_csv_dir: /kaggle/input/save_series_csv/csvs

feature:
    agg_freq: 24 # [step]

env:
    seed: 46
    num_threads: 30

1st_stage:
    execution:
        exp_id: exp_071
        best_exp_id: exp_071
    xgboost:
        objective: binary:logistic
        learning_rate: 0.1
        reg_alpha: 0.02
        reg_lambda: 0.2
        random_state: 42
        max_depth: 5
        colsample_bytree: 0.7
        tree_method: gpu_hist

2nd_stage:
    execution:
        exp_id: exp_097
        best_exp_id: exp_097
        agg_freq: 24 # [step]
    xgboost:
        objective: reg:squarederror
        learning_rate: 0.01
        reg_alpha: 0.02
        reg_lambda: 0.2
        random_state: 42
        max_depth: 5
        colsample_bytree: 0.7
        tree_method: gpu_hist

patch_model:
    execution:
        exp_id: exp_105
        best_exp_id: exp_093
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        num_layers: 4
        dim_feedforward: 128
        model_size: 128

conv1d_gru_model:
    execution:
        exp_id: exp_106
        best_exp_id: exp_100
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        model_size: 128

spectrogram:
    execution:
        exp_id: exp_098
        best_exp_id: None
        block_size: 3840 # 12step x 320min
        image_size: 320
        hop_length: 12
        n_fft: 639

ensemble:
    execution:
        exp_id: exp_084
        best_exp_id: exp_084
