dataset:
    competition_dir: /kaggle/input/child-mind-institute-detect-sleep-states
    cv_split_path: /kaggle/input/cv-split/train_folds.csv
    train_base_path: /kaggle/input/train_base/train_base.csv
    step_csv_dir: /kaggle/input/save_series_csv/csvs_gaussian

env:
    seed: 46
    num_threads: 30

xgb_model:
    execution:
        exp_id: exp_153
        best_exp_id: exp_153
        agg_freq: 12 # [step]
    xgboost:
        objective: reg:squarederror
        learning_rate: 0.01
        reg_alpha: 609.0209739686968
        reg_lambda: 0.0012784881051895653
        max_depth: 7
        colsample_bytree: 0.7716653154458131
        subsample: 0.7535747757020815
        tree_method: gpu_hist
        random_state: 42

lgb_model:
    execution:
        exp_id: exp_154
        best_exp_id: exp_154
        agg_freq: 12 # [step]
    lightgbm:
        objective: regression
        learning_rate: 0.01
        reg_alpha: 1.00853
        reg_lambda: 10.326107
        max_depth: 9
        num_leaves: 33
        colsample_bytree: 0.454097
        n_estimators: 1000000
        random_state: 42

patch_transformer_gru:
    execution:
        exp_id: exp_150
        best_exp_id: exp_150
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        num_layers: 4
        dim_feedforward: 128
        model_size: 128
        dropout: 0.0

patch_transformer_gru_v2:
    execution:
        exp_id: exp_160
        best_exp_id: exp_160
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        num_layers: 4
        dim_feedforward: 128
        model_size: 128
        dropout: 0.0

patch_wavenet_gru:
    execution:
        exp_id: exp_151
        best_exp_id: exp_151
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        model_size: 128
        linear_out: 128
        dropout: 0.0

patch_wavenet_gru_v2:
    execution:
        exp_id: exp_161
        best_exp_id: exp_161
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        model_size: 128
        linear_out: 128
        dropout: 0.0

patch_1dcnn_gru:
    execution:
        exp_id: exp_152
        best_exp_id: exp_152
        block_size: 19200 # 12 x 8 * 200
        patch_size: 12
    params:
        numeraical_linear_size: 168
        model_size: 128

spectrogram:
    execution:
        exp_id: exp_098
        best_exp_id: None
        block_size: 3840 # 12step x 320min
        image_size: 320
        hop_length: 12
        n_fft: 639

ensemble:
    execution:
        exp_id: exp_ensemble
        best_exp_id: exp_ensemble

stacking:
    execution:
        exp_id: exp_125
        best_exp_id: exp_125
        block_size: 5760 # 12step x 480min
        models: ["xgb_model", "lgb_model", "patch_transformer_gru"]
        patch_size: 6
    params:
        numeraical_linear_size: 168
        model_size: 128
